# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'PhotoDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoDemo

  target 'PhotoDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'LYSPhotoKit', '~> 0.0.4'
end
